version: "3"
services:
#  web:
#    image: 'webstart:3'
#    container_name: 'stack_web'
#    ports:
#     # external:internal
#      - '8080:8080'
#    networks:
#      - outside
#    depends_on:
#      - db
#    deploy:
#      restart_policy:
#        condition: on-failure
  db:
    image: 'neo4j:latest'
    ports:
      - '7474:7474'
      - '7687:7687'
#    networks:
#      - outside
    volumes:
      - ./neo4j:/data
#networks:
#  outside:
