version: "3"
services:
  web:
    image: 'nickpearce/webstart'
    ports:
     # external:internal
      - '8081:8080'
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
