version: "3"
services:
  db:
    image: 'calproc-db:1'
    ports:
      - '7474:7474'
      - '7687:7687'
    networks:
      - outside
    volumes:
      - ./db/import-mapped:/var/lib/neo4j/import
      - ./db/conf-mapped:/var/lib/neo4j/conf
networks:
  outside:
